// Generated by CoffeeScript 1.3.3
(function() {
  var Presentation, root;

  Presentation = (function() {

    function Presentation(options) {
      this.html = options.html;
      this.$ = options.jquery;
    }

    Presentation.prototype.toDOMTree = function() {
      var currentSlide, nodes, notes, result,
        _this = this;
      nodes = this.$(this.html);
      result = this.$('<div/>');
      currentSlide = null;
      notes = null;
      nodes.each(function(_, node) {
        var container;
        node = _this.$(node);
        if (node.is('h1')) {
          if (currentSlide != null) {
            result.append(currentSlide);
          }
          currentSlide = _this.newSlide();
          notes = null;
        }
        if ((container = currentSlide) != null) {
          if (node.is('hr')) {
            notes = node = _this.newNotes();
          } else {
            if (notes != null) {
              container = notes;
            }
          }
          return container.append(node);
        }
      });
      if (currentSlide != null) {
        result.append(currentSlide);
      }
      return result;
    };

    Presentation.prototype.newSlide = function() {
      return this.$('<section/>');
    };

    Presentation.prototype.newNotes = function() {
      return this.$('<div class="notes"/>');
    };

    return Presentation;

  })();

  root = typeof exports !== "undefined" && exports !== null ? exports : window;

  root.Presentation = Presentation;

}).call(this);
