// Generated by CoffeeScript 1.3.3
(function() {

  $(function() {
    var success;
    success = function(text) {
      var presentation, view;
      presentation = new Presentation({
        html: markdown.toHTML(text),
        jquery: $
      });
      $('body').html('');
      view = new PresentationView({
        presentation: presentation,
        container: $('body')
      });
      view.showSlide(0);
      document.onkeydown = function(e) {
        switch (e.which) {
          case 37:
            return view.goBack();
          case 39:
            return view.advance();
        }
      };
      $('code').attr('data-language', 'javascript');
      return Rainbow.color();
    };
    return $.ajax('./presentation.mkd', {
      success: success,
      error: function() {
        return alert('error ' + arguments);
      }
    });
  });

}).call(this);
